import { useMemo, useState } from 'react';

const E = 'lakizaAdminSchedulerEvents';
const C = 'lakizaClientProfiles';
const read = (k, f) => { try { return JSON.parse(localStorage.getItem(k)) || f; } catch { return f; } };
const save = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} };
const today = () => new Date().toISOString().slice(0, 10);
const digits = (v) => String(v || '').replace(/\D/g, '');
const cid = (e) => e.clientId || `client-${digits(e.phone)}`;
const dt = (e) => `${e.date || '0000-00-00'}T${e.time || '00:00'}`;
const norm = (v) => String(v || '').toLowerCase().replace(/ё/g, 'е');
const wd = (d) => new Intl.DateTimeFormat('ru-RU', { weekday: 'long' }).format(new Date(`${d}T12:00:00`));
const mon = (d) => new Intl.DateTimeFormat('ru-RU', { month: 'long', year: 'numeric' }).format(new Date(`${d}T12:00:00`));
const m0 = (d) => { const x = new Date(`${d}T12:00:00`); x.setDate(1); return x.toISOString().slice(0, 10); };
const addM = (d, n) => { const x = new Date(`${d}T12:00:00`); x.setDate(1); x.setMonth(x.getMonth() + n); return x.toISOString().slice(0, 10); };
const days = (m) => { const first = new Date(`${m0(m)}T12:00:00`); const off = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - off); return Array.from({ length: 42 }, (_, i) => { const x = new Date(start); x.setDate(start.getDate() + i); return x.toISOString().slice(0, 10); }); };
const bmi = (w, h) => Number(w) > 0 && Number(h) > 0 ? (Number(w) / ((Number(h) / 100) ** 2)).toFixed(1) : '—';
const sl = (s) => ({ new: 'заявка', confirmed: 'подтверждена', done: 'завершена', cancelled: 'отменена', change: 'согласовать' }[s] || s || 'заявка');
function stat(ev) { const sorted = [...ev].sort((a, b) => dt(a).localeCompare(dt(b))); const measured = sorted.filter((x) => Number(x.weight) > 0); const hrs = sorted.reduce((s, x) => s + Number(x.duration || 0), 0) / 60; const diff = measured.length > 1 ? Number(measured.at(-1).weight) - Number(measured[0].weight) : null; return { total: sorted.length, done: sorted.filter((x) => x.status === 'done').length, future: sorted.filter((x) => dt(x) >= `${today()}T00:00` && x.status !== 'cancelled').length, hours: hrs.toFixed(1), delta: diff === null ? '—' : `${diff > 0 ? '+' : ''}${diff.toFixed(1)} кг`, measured }; }

export default function AdminStatsConsolePlus() {
  const [open, setOpen] = useState(false), [q, setQ] = useState(''), [sel, setSel] = useState(''), [v, setV] = useState(0);
  const events = useMemo(() => read(E, []), [v]);
  const clients = useMemo(() => read(C, []), [v]);
  const rows = useMemo(() => { const map = new Map(); events.forEach((e) => { const id = cid(e); if (!map.has(id)) map.set(id, []); map.get(id).push(e); }); return [...map.entries()].map(([id, ev]) => { const saved = clients.find((c) => c.id === id) || {}; const f = ev[0] || {}; const client = { id, name: saved.name || f.client || 'Клиент', phone: saved.phone || f.phone || '', email: saved.email || '', privateNotes: saved.privateNotes || f.note || '' }; return { id, client, events: ev, stat: stat(ev) }; }).sort((a,b)=>a.client.name.localeCompare(b.client.name,'ru')); }, [events, clients]);
  const filtered = rows.filter((r) => !q || norm(`${r.client.name} ${r.client.phone} ${r.client.privateNotes} ${r.events.map((e)=>`${e.service} ${e.note} ${e.date}`).join(' ')}`).includes(norm(q)) || digits(r.client.phone).includes(digits(q)));
  const selected = rows.find((r) => r.id === sel);
  const refresh = () => setV((x) => x + 1);
  const updateEvent = (id, patch) => { const item = events.find((e) => e.id === id); if (!item || !confirm(`Сохранить изменения ${item.date} ${item.time}?`)) return; save(E, events.map((e) => e.id === id ? { ...e, ...patch } : e)); refresh(); };
  const removeEvent = (id) => { const item = events.find((e) => e.id === id); if (!item || !confirm(`Удалить сеанс ${item.date} ${item.time}?`)) return; save(E, events.filter((e) => e.id !== id)); refresh(); };
  const saveNote = (client, note) => { const exists = clients.some((c) => c.id === client.id); save(C, exists ? clients.map((c) => c.id === client.id ? { ...c, privateNotes: note } : c) : [...clients, { ...client, privateNotes: note }]); refresh(); };
  return <><button type="button" onClick={() => setOpen(true)} className="fixed bottom-24 right-3 z-[70] rounded-full bg-lime-200 px-4 py-3 text-xs font-black text-emerald-950 shadow-2xl shadow-black/50">Статистика</button>{open && <div className="fixed inset-0 z-[90] overflow-y-auto bg-black/70 p-2 text-white backdrop-blur-sm"><div className="mx-auto my-4 max-w-4xl rounded-[1.5rem] border border-white/10 bg-[#07140e] p-3 shadow-2xl shadow-black md:p-5"><div className="mb-3 flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-lime-300/60">администратор</div><h2 className="text-3xl font-black tracking-[-.06em] text-lime-50">Статистика и сеансы</h2><p className="mt-1 text-sm text-emerald-50/55">календарь, все сеансы, переносы, согласование</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Закрыть</button></div>{selected ? <Detail row={selected} back={() => setSel('')} updateEvent={updateEvent} removeEvent={removeEvent} saveNote={saveNote} /> : <List q={q} setQ={setQ} rows={filtered} setSel={setSel} />}</div></div>}</>;
}
function List({ q, setQ, rows, setSel }) { return <div><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Поиск: имя, телефон, услуга, заметка" className="mb-3 w-full rounded-2xl bg-white px-4 py-4 text-sm font-bold text-emerald-950 outline-none" /><div className="grid gap-2 md:grid-cols-2">{rows.map((r) => <button key={r.id} onClick={() => setSel(r.id)} className="rounded-2xl bg-white/10 p-3 text-left"><b className="block truncate text-lg text-lime-100">{r.client.name}</b><span className="text-xs text-emerald-50/55">{r.client.phone}</span><div className="mt-3 grid grid-cols-3 gap-1"><Mini label="сеансов" value={r.stat.total} /><Mini label="часов" value={r.stat.hours} /><Mini label="вес" value={r.stat.delta} /></div></button>)}</div></div>; }
function Detail({ row, back, updateEvent, removeEvent, saveNote }) { const [sec, setSec] = useState('all'); const [month, setMonth] = useState(m0(today())); const [note, setNote] = useState(row.client.privateNotes || ''); const sorted = [...row.events].sort((a,b)=>dt(a).localeCompare(dt(b))); const future = sorted.filter((e)=>dt(e)>=`${today()}T00:00` && e.status !== 'cancelled'); const history = sorted.filter((e)=>dt(e)<`${today()}T00:00` || ['done','cancelled'].includes(e.status)); const shown = sec === 'future' ? future : sec === 'history' ? history : sorted; return <div><button onClick={back} className="mb-3 rounded-full bg-white/10 px-4 py-2 text-xs font-black">← список</button><div className="rounded-2xl bg-lime-200/10 p-3"><h3 className="text-2xl font-black text-lime-50">{row.client.name}</h3><p className="text-sm text-emerald-50/55">{row.client.phone}</p></div><div className="mt-3 grid gap-2 sm:grid-cols-5"><Stat onClick={()=>setSec('all')} label="всего" value={row.stat.total}/><Stat onClick={()=>setSec('future')} label="будущие" value={row.stat.future}/><Stat onClick={()=>setSec('history')} label="завершено" value={row.stat.done}/><Stat onClick={()=>setSec('metrics')} label="вес" value={row.stat.delta}/><Stat onClick={()=>setSec('all')} label="ближ." value={future[0] ? `${future[0].date.slice(5)} ${future[0].time}` : '—'}/></div><div className="mt-3 grid grid-cols-5 gap-1 rounded-2xl bg-white/10 p-1"><Tab id="all" sec={sec} setSec={setSec} t="Все"/><Tab id="future" sec={sec} setSec={setSec} t="Будущие"/><Tab id="history" sec={sec} setSec={setSec} t="История"/><Tab id="calendar" sec={sec} setSec={setSec} t="Календарь"/><Tab id="metrics" sec={sec} setSec={setSec} t="Вес"/></div>{sec === 'calendar' && <Cal events={sorted} month={month} setMonth={setMonth}/>} {sec === 'metrics' && <Chart events={row.stat.measured}/>} {sec !== 'calendar' && sec !== 'metrics' && <div className="mt-3 grid gap-2">{shown.map((e)=><Editor key={e.id} event={e} updateEvent={updateEvent} removeEvent={removeEvent}/>)}</div>}<label className="mt-3 block"><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-lime-200/60">закрытые пометки</span><textarea value={note} onChange={(e)=>setNote(e.target.value)} rows={4} className="w-full rounded-2xl bg-white px-4 py-3 text-sm font-bold text-emerald-950" /></label><button onClick={()=>saveNote(row.client,note)} className="mt-2 rounded-full bg-lime-200 px-4 py-2 text-xs font-black text-emerald-950">Сохранить заметку</button></div>; }
function Cal({ events, month, setMonth }) { const counts = new Map(); events.forEach((e)=>counts.set(e.date,(counts.get(e.date)||0)+1)); return <div className="mt-3 rounded-2xl bg-white/10 p-3"><div className="mb-2 flex items-center justify-between"><button onClick={()=>setMonth(addM(month,-1))} className="rounded-xl bg-white/10 px-3 py-2 font-black">‹</button><b className="capitalize text-lime-100">{mon(month)}</b><button onClick={()=>setMonth(addM(month,1))} className="rounded-xl bg-white/10 px-3 py-2 font-black">›</button></div><div className="grid grid-cols-7 gap-1 text-center text-[9px] text-emerald-50/45"><span>пн</span><span>вт</span><span>ср</span><span>чт</span><span>пт</span><span>сб</span><span>вс</span></div><div className="mt-1 grid grid-cols-7 gap-1">{days(month).map((d)=><div key={d} className={`relative rounded-xl px-1 py-2 text-center ${counts.get(d)?'bg-lime-200 text-emerald-950':'bg-white/10 text-emerald-50/45'}`}><b className="block text-xs">{d.slice(8)}</b><span className="text-[8px]">{wd(d).slice(0,2)}</span>{counts.get(d)&&<em className="absolute right-0 top-0 rounded-full bg-emerald-950 px-1 text-[8px] font-black not-italic text-lime-100">{counts.get(d)}</em>}</div>)}</div></div>; }
function Editor({ event, updateEvent, removeEvent }) { const [d,setD] = useState(event); const set=(k,v)=>setD((p)=>({...p,[k]:v})); const move=()=>updateEvent(event.id,{...d,status:'change',note:`${d.note||''} Требуется согласование переноса.`.trim()}); return <div className="rounded-2xl bg-white/10 p-3"><div className="mb-2 text-xs font-black uppercase tracking-[.12em] text-lime-200/70">{event.date} · {wd(event.date)} · {event.time} · {sl(event.status)}</div><div className="grid gap-2 sm:grid-cols-3"><F label="Дата" type="date" value={d.date||''} set={(v)=>set('date',v)}/><F label="Время" value={d.time||''} set={(v)=>set('time',v)}/><S value={d.status||'new'} set={(v)=>set('status',v)}/><F label="Услуга" value={d.service||''} set={(v)=>set('service',v)}/><F label="Минут" value={String(d.duration||'')} set={(v)=>set('duration',v)}/><F label="Вес" value={String(d.weight||'')} set={(v)=>set('weight',v)}/><F label="Рост" value={String(d.height||'')} set={(v)=>set('height',v)}/></div><textarea value={d.note||''} onChange={(e)=>set('note',e.target.value)} rows={2} className="mt-2 w-full rounded-xl bg-white px-3 py-2 text-sm font-bold text-emerald-950" /><div className="mt-2 flex flex-wrap gap-2"><button onClick={()=>updateEvent(event.id,d)} className="rounded-full bg-lime-200 px-4 py-2 text-xs font-black text-emerald-950">Сохранить</button><button onClick={move} className="rounded-full bg-blue-500/25 px-4 py-2 text-xs font-black text-blue-100">Перенести / согласовать</button><button onClick={()=>removeEvent(event.id)} className="rounded-full bg-red-500/20 px-4 py-2 text-xs font-black text-red-100">Удалить</button></div></div>; }
function Chart({events}){ if(events.length<2)return <div className="mt-3 rounded-2xl border border-dashed border-white/20 p-5 text-center text-emerald-50/55">Нужно минимум два замера.</div>; const w=events.map((e)=>Number(e.weight)); const min=Math.min(...w)-.5, max=Math.max(...w)+.5; return <div className="mt-3 rounded-2xl bg-white/10 p-3"><div className="mb-2 text-xs font-black text-lime-200/70">Вес: {w[0]} → {w.at(-1)} кг</div><div className="relative h-36 rounded-xl bg-black/25">{events.map((e,i)=>{const x=(i/(events.length-1))*100,y=100-((Number(e.weight)-min)/(max-min))*100;return <b key={e.id} className="absolute -translate-x-1/2 -translate-y-1/2 rounded bg-lime-200 px-1 text-[9px] text-emerald-950" style={{left:`${x}%`,top:`${y}%`}}>{e.weight}</b>})}</div></div>}
function F({label,value,set,type='text'}){return <label><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-lime-200/60">{label}</span><input type={type} value={value} onChange={(e)=>set(e.target.value)} className="w-full rounded-xl bg-white px-3 py-2 text-sm font-bold text-emerald-950"/></label>}
function S({value,set}){return <label><span className="mb-1 block text-[10px] font-black uppercase tracking-[.14em] text-lime-200/60">Статус</span><select value={value} onChange={(e)=>set(e.target.value)} className="w-full rounded-xl bg-white px-3 py-2 text-sm font-bold text-emerald-950"><option value="new">заявка</option><option value="confirmed">подтверждена</option><option value="done">завершена</option><option value="change">согласовать</option><option value="cancelled">отменена</option></select></label>}
function Tab({id,sec,setSec,t}){return <button onClick={()=>setSec(id)} className={`rounded-xl px-1 py-2 text-[10px] font-black ${sec===id?'bg-lime-200 text-emerald-950':'bg-white/10 text-emerald-50/70'}`}>{t}</button>}
function Stat({label,value,onClick}){return <button onClick={onClick} className="rounded-xl bg-white/10 p-3 text-left"><div className="text-[9px] font-black uppercase tracking-[.14em] text-lime-200/55">{label}</div><b className="mt-1 block truncate text-xl text-lime-100">{value}</b></button>}
function Mini({label,value}){return <div className="rounded-xl bg-black/20 px-2 py-1"><div className="text-[8px] font-black uppercase tracking-[.1em] text-lime-200/50">{label}</div><b className="text-xs text-lime-100">{value}</b></div>}
